#!/usr/bin/env python3
"""
190 Expanded Wiki - "Changes from Vanilla" page data
====================================================

Converts the changelog Markdown into the data files behind total_war/changes.html:

    ../CHANGES.md                      -> ../total_war/data/changes.js          (CHANGES_DOCS.main)
    ../changes/APPENDIX_190E.md        -> ../total_war/data/changes_190e.js     (CHANGES_DOCS.t190e)
    ../changes/APPENDIX_CAMPAIGN.md    -> ../total_war/data/changes_campaign.js (CHANGES_DOCS.campaign)
    ../changes/APPENDIX_BATTLE.md      -> ../total_war/data/changes_battle.js   (CHANGES_DOCS.battle)

    python build_changes.py [--dry-run]

The appendices are big generated stat tables, so each gets its own file and the page loads it
only when its tab is opened. Markdown conversion reuses fetch_tool_docs.convert(), so the same
subset rules apply (flat lists, pipe tables, asterisk-only emphasis, allow-listed HTML).

The Markdown itself is produced from the mod trees by
Z:\\Claude\\190Expanded\\tools\\changelog (lc_merge.py -> stat_tables.py -> assemble.py).
"""

import io
import json
import os
import sys

from fetch_tool_docs import convert, ROOT, DATA

DOCS = [
    # id, source (relative to ROOT), output file, title
    ("main", "CHANGES.md", "changes.js", "Changes from Vanilla"),
    ("t190e", os.path.join("changes", "APPENDIX_190E.md"), "changes_190e.js", "190E stat tables"),
    ("campaign", os.path.join("changes", "APPENDIX_CAMPAIGN.md"), "changes_campaign.js", "Campaign Overhaul tables"),
    ("battle", os.path.join("changes", "APPENDIX_BATTLE.md"), "changes_battle.js", "Battle Overhaul tables"),
]

BANNER = """// data/%s
// GENERATED by generate_data/build_changes.py - do not edit by hand.
// Source: %s"""


def main():
    dry_run = "--dry-run" in sys.argv[1:]
    print("changes page")
    missing = 0
    for doc_id, src, out, title in DOCS:
        path = os.path.join(ROOT, src)
        if not os.path.exists(path):
            print("  ! missing %s" % path)
            missing += 1
            continue
        md = io.open(path, encoding="utf-8").read()
        sections = convert(md)
        payload = {"id": doc_id, "title": title, "file": src.replace("\\", "/"), "sections": sections}
        # each file registers itself on a shared global, so they can load in any order
        text = ("%s\nwindow.CHANGES_DOCS = window.CHANGES_DOCS || {};\nwindow.CHANGES_DOCS[%s] = %s;\n"
                % (BANNER % (out, src.replace("\\", "/")), json.dumps(doc_id),
                   json.dumps(payload, ensure_ascii=False, separators=(",", ":"))))
        dest = os.path.join(DATA, out)
        size = len(text.encode("utf-8")) / 1024
        if dry_run:
            print("  (dry run) %-28s %5d sections  [%.1f KB]" % (out, len(sections), size))
            continue
        with io.open(dest, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        print("  wrote %-28s %5d sections  [%.1f KB]" % (out, len(sections), size))
    return 1 if missing == len(DOCS) else 0


if __name__ == "__main__":
    sys.exit(main())
