backend:
  name: git-gateway
  branch: main
  identity_url: "https://effortless-chaja-98f0d7.netlify.app/.netlify/identity"
  gateway_url: "https://effortless-chaja-98f0d7.netlify.app/.netlify/git"

site_url: https://ironictw2st.github.io  # Add this line!
display_url: https://ironictw2st.github.io  # And this line!

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "characters"
    label: "Characters"
    folder: "_characters"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "character"}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Chinese Name", name: "chinese_name", widget: "string", required: false}
      - {label: "Faction", name: "faction", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Bio", name: "body", widget: "markdown"}
      
  - name: "data"
    label: "Character Data"
    files:
      - label: "Characters JSON"
        name: "characters"
        file: "_data/characters.json"
        fields:
          - label: Characters
            name: characters
            widget: list
            fields:
              - {label: "ID", name: "id", widget: "string"}
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Biography", name: "bio", widget: "text"}
              - {label: "Image", name: "image", widget: "string"}
              - {label: "Faction", name: "faction", widget: "string"}